version: "3.9"

services:
  mysql:
    image: mysql:latest
    container_name: jwt-study-mysql
    ports:
      - ${MYSQL_PORT}:3306
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}


  redis:
    image: redis:latest
    container_name: jwt-study-redis
    ports:
      - ${REDIS_PORT}:6379
    restart: always
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD}
